name: Trigger auto deployment for alwayson

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/alwayson-AutoDeployTrigger-ffff72a6-f02d-4929-aaae-80cc97ef9505.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: alwayson.azurecr.io
          username: ${{ secrets.ALWAYSON_REGISTRY_USERNAME }}
          password: ${{ secrets.ALWAYSON_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: alwayson.azurecr.io/alwayson:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALWAYSON_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n alwayson -g alwayson --server alwayson.azurecr.io --username  ${{ secrets.ALWAYSON_REGISTRY_USERNAME }} --password ${{ secrets.ALWAYSON_REGISTRY_PASSWORD }}
            az containerapp update -n alwayson -g alwayson --image alwayson.azurecr.io/alwayson:${{ github.sha }}
