# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myslots

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https:// ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cf25fbcd7f204624bd9aa28ff9a3c9f6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0c5d4a3b65234952b7047af91879a30b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:  ghcr.io/${{ secrets.AzureAppService_ContainerUsername_cf25fbcd7f204624bd9aa28ff9a3c9f6 }}/sayedimac/slots:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myslots'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a2da578c81f14ceaabec8662be06d1e9 }}
        images: ' ghcr.io/${{ secrets.AzureAppService_ContainerUsername_cf25fbcd7f204624bd9aa28ff9a3c9f6 }}/sayedimac/slots:${{ github.sha }}'